<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
	  <Folder Include="Fonts\" />
	  <Folder Include="Images\" />
	  <Folder Include="ViewModels\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Config\GoogleSheetsConfig.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <Target Name="UnblockDlls" AfterTargets="Build">
    <Exec Command="powershell.exe -Command &quot;Get-ChildItem -Path '$(OutDir)' -Recurse -Filter '*.dll' -ErrorAction SilentlyContinue | ForEach-Object { Remove-Item -Path ($_.FullName + ':Zone.Identifier') -ErrorAction SilentlyContinue; $_ | Unblock-File -ErrorAction SilentlyContinue }; Write-Host 'Unblocked all DLLs'&quot;" ContinueOnError="true" />
  </Target>

</Project>
